#!/usr/bin/python
"""
Electobot
by Philip Brien (http://github.com/ZsigE)

Analysis and prediction tool based on the 2010 UK General Election results

Main module and data structures
"""

# Python imports
import argparse
import os
import cPickle as pickle
import logging
from operator import attrgetter

# Electobot imports
import csvparser
import utils
from constants import *
from candidate import Candidate
from constituency import Constituency
from montecarlo import MonteCarlo

# Set up logging
logger = logging.getLogger("electobot")

# Classes
class Election(object):
    """Master class containing all information about the election."""
    
    def __init__(self):
        """Constructor."""
        
        # Data used to run the election
        self.constituencies = {}
        self.predicted_support = {}
        
        # Data generated by running the election
        self.parties = {}
        self.swing_matrix = {}
        
        # Data generated by analyzing the results
        self.result = None
        
        return
        
    def populate_from_csv(self, csv_filename):
        """Create an Election from saved election data in CSV format."""
        
        # Extract all the information from the CSV file.
        rows = csvparser.csv_to_dicts(csv_filename)
        logger.debug("Found {0} rows".format(len(rows)))
           
        for row in rows:
            const = row["Seat"]
            logger.debug("Found seat {0}".format(const))
            if const not in self.constituencies:
                c = Constituency(const, self)
                self.constituencies[const] = c
            else:
                c = self.constituencies[const]
            c.region = row["Region"]
            candidates_2010 = row.candidates()
            c.votes_2005 = row.votes(2005)
            c.votes_2010 = row.votes(2010)
            c.turnout_2005 = float(row["Turn05"])
            c.turnout_2010 = float(row["Turn10"])

            # Copy the votes into the Candidate structures.
            c.candidates_2010 = []
            for party in c.votes_2010.keys():
                if party in candidates_2010.keys():
                    name = candidates_2010[party]
                else:
                    name = "Unknown"
                candidate = Candidate(name, party, c.votes_2010[party])
                c.candidates_2010.append(candidate)
                            
        return
    
    def add_total_2010_votes(self):
        """Fill in the total votes for 2010 for each constituency from the
        Guardian data and fix up the 'Other' category.
        """
        
        total_votes = csvparser.get_total_votes_from_guardian()
        
        for const_name in self.constituencies.keys():
            const = self.constituencies[const_name]
            del const.votes_2010[OTH]
            non_other_votes = sum(const.votes_2010.values())
            const.votes_2010[OTH] = total_votes[const_name] - non_other_votes
            
        return

    def prepare_predicted_support(self):
        """Do some tidy-up work on the predicted support so we can use it."""
        
        # If a party has no support recorded, remove them entirely - we'll treat
        # them as part of the "Other" pot.
        for party in self.predicted_support.keys():
            if self.predicted_support[party] == 0:
                del self.predicted_support[party]
            else:
                # Express the support as a ratio, not a percentage - this makes
                # the maths much easier.
                self.predicted_support[party] = \
                                           (self.predicted_support[party] / 100)
        
        # Fill in "Other" support automatically, to guarantee the support adds up
        # to 100.
        self.predicted_support[OTH] = (1 - sum(self.predicted_support.values()))
        
        return        
   
    def calculate_overall_support(self, year=None):
        """Create a support dictionary based on the number of votes in the
        given year.  If no year is provided, use the predicted votes.
        """
        
        support = {}
        for const_name in self.constituencies.keys():
            const = self.constituencies[const_name]
            if year is None:
                votes = const.sim_votes
            elif year == 2005:
                votes = const.votes_2005
            else:
                assert year == 2010, "Year must be None, 2005 or 2010"
                votes = const.votes_2010
            for party in votes.keys():
                if party not in support.keys():
                    support[party] = votes[party]
                else:
                    support[party] += votes[party]
                    
        return support
                
    def predict_votes(self):
        """Predict the numbers of votes in each constituency."""
        
        # Calculate the overall swing matrix.
        support_2010 = self.calculate_overall_support(2010)
        self.swing_matrix = utils.calculate_swing(support_2010,
                                                  self.predicted_support)
        
        # Now use that to predict each constituency's vote distribution.
        for const_name in self.constituencies:
            const = self.constituencies[const_name]
            const.predict_votes(self.predicted_support)
            
        return
    
    def simulate(self):
        """Simulate the outcome of this election."""
        
        for const_name in self.constituencies:
            const = self.constituencies[const_name]
            const.simulate()
            
            # Add the seat to the winning party's total.
            if const.winning_party in self.parties.keys():          
                self.parties[const.winning_party].seats += 1
            else:
                party = Party(const.winning_party)
                party.seats = 1
                self.parties[const.winning_party] = party
        
        return
    
    def analyze(self):
        """Analyze the results of the election."""
        
        # Create a new Result structure to hold these results.
        self.result = Result()
        
        # First determine the largest party.
        party_list = sorted(self.parties.values(),
                            key=attrgetter('seats'),
                            reverse=True)
        self.result.largest_party = party_list[0].name
        self.result.most_seats_won = party_list[0].seats

        # Also determine the runner-up and third-place parties.
        self.result.runner_up = party_list[1].name
        self.result.third_place = party_list[2].name
                
        # Now determine whether the largest party is past or behind the winning
        # line (and by how much).
        self.result.margin_of_victory = (self.result.most_seats_won - 
                                         NEEDED_FOR_MAJORITY)
        if self.result.margin_of_victory >= 0:
            self.result.summary = "{0} victory (majority {1})".format(
                                                  self.result.largest_party,
                                                  self.result.margin_of_victory)
        else:
            self.result.summary = "Hung Parliament ({0} needs {1})".format(
                                            self.result.largest_party,
                                            (0 - self.result.margin_of_victory))
            
        # Did UKIP win any seats in this election?
        if UKP in self.parties:
            self.result.ukip_seats = self.parties[UKP].seats
        else:
            self.result.ukip_seats = 0
        
        # Did the Lib-Dems?
        if LD in self.parties:
            self.result.libdem_seats = self.parties[LD].seats
        else:
            self.result.libdem_seats = 0
        
        # Did the Greens hold Brighton Pavilion?
        if self.constituencies["Brighton Pavilion"].winning_party == GRN:
            self.result.greens_hold_brighton = True
        else:
            self.result.greens_hold_brighton = False
            
        # Was the party with the most seats the popular vote winner?
        votes = {}
        for const_name in self.constituencies:
            const = self.constituencies[const_name]
            for party in const.sim_votes.keys():
                if party not in votes.keys():
                    votes[party] = const.sim_votes[party]
                else:
                    votes[party] += const.sim_votes[party]
                    
        most_votes = 0
        self.result.most_votes_party = None
        for party in votes.keys():
            if votes[party] > most_votes:
                most_votes = votes[party]
                self.result.most_votes_party = party
                
        self.result.seat_winner_is_pop_winner = (self.result.largest_party ==
                                                 self.result.most_votes_party)
        
        
        return
    
    def run(self):
        """Run the whole election."""
        
        self.predict_votes()
        self.simulate()
        self.analyze()
        
        return

class Party(object):
    """Political party.  Used to classify Candidates."""
    
    def __init__(self, name):
        """Constructor.  Store just the name."""
        
        self.name = name
        self.seats = 0
        
        return

class Result(object):
    """Result of the election, including all the information we might want to
    know about.
    """
    
    def __init__(self):
        """Constructor.  Initialize instance variables."""
        
        self.summary = ""  # One-line summary of the election result
        self.winner = None  # None represents a hung parliament
        self.largest_party = None
        self.runner_up = None
        self.third_place = None
        self.most_votes_party = None
        self.margin_of_victory = 0
        self.most_seats_won = 0
        self.ukip_seats = 0  
        self.libdem_seats = 0  
        self.greens_hold_brighton = False
        self.seat_winner_is_pop_winner = False   
    
# Functions
def electobot():
    """Main function."""

    # Set up logging.
    formatter = logging.Formatter('%(asctime)s - %(name)s - '
                                  '%(levelname)s - %(message)s')
    handler = logging.FileHandler(LOG_FILE, mode="w")
    handler.setFormatter(formatter)
    logger.setLevel(LOG_LEVEL)
    logger.addHandler(handler)
     
    # Parse the input arguments.
    parser = argparse.ArgumentParser()
    fileopts = parser.add_argument_group("File options")
    fileopts.add_argument("--csv", "-c",
                         help="CSV file containing election data",
                         action="store", dest="csv")
    fileopts.add_argument("--pickle", "-p",
                          help="File containing pickled election data",
                          action="store",
                          dest="pickle")
    fileopts.add_argument("--savefile", "-s", 
                          help="Filename for saving pickled election data",
                          action="store",
                          dest="savefile")
    
    simopts = parser.add_argument_group("Simulation options")
    simopts.add_argument("--single-election", "-1",
                         help="Simulate a single election",
                         action="store_true",
                         dest="single_election")
    simopts.add_argument("--montecarlo", "-m",
                         help="Run a Monte Carlo simulation",
                         action="store",
                         type=int,
                         default=0,
                         dest="iterations")
    
    partyopts = parser.add_argument_group("Party support options")
    partyopts.add_argument("--conservative", "-t",
                           help="Predicted percentage of Conservative support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="conservative")
    partyopts.add_argument("--labour", "-l",
                           help="Predicted percentage of Labour support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="labour")
    partyopts.add_argument("--libdem", "-d",
                           help="Predicted percentage of Lib-Dem support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="libdem")
    partyopts.add_argument("--green", "-g",
                           help="Predicted percentage of Green support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="green")
    partyopts.add_argument("--ukip", "-u",
                           help="Predicted percentage of UKIP support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="ukip")
    partyopts.add_argument("--snp", "-n",
                           help="Predicted percentage of SNP support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="snp")
    partyopts.add_argument("--plaid-cymru", "-w",
                           help="Predicted percentage of Plaid Cymru support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="plaid")
    partyopts.add_argument("--bnp", "-z",
                           help="Predicted percentage of BNP support",
                           action="store",
                           type=float,
                           default=0.0,
                           dest="bnp")

    opts = parser.parse_args()
    
    election = None
    if opts.csv:
        # Populate the election from a CSV file.
        assert os.path.exists(opts.csv), "{0} does not exist".format(opts.csv)
        election = Election()
        election.populate_from_csv(opts.csv)
        
        # For no apparent reason, the Harvard data does not include the total
        # votes cast in each constituency in 2010.  Fill this in from the 
        # Guardian data instead.
        election.add_total_2010_votes()
        
    elif opts.pickle:
        # Restore a saved election file from the pickled representation.
        assert os.path.exists(opts.pickle),                                    \
            "{0} does not exist".format(opts.pickle)
        with open(opts.pickle, "rb") as pickle_file:
            election = pickle.load(pickle_file)
        
    if opts.savefile:
        assert os.path.exists(opts.savefile),                                  \
            "{0} does not exist".format(opts.savefile)
        with open(opts.savefile, "wb") as save_file:
            pickle.dump(election, save_file, protocol=0)
    
    # Fill in the support for each party from the command-line arguments.
    election.predicted_support = {
                                  CON: opts.conservative,
                                  LAB: opts.labour,
                                  LD: opts.libdem,
                                  SNP: opts.snp,
                                  PC: opts.plaid,
                                  GRN: opts.green,
                                  BNP: opts.bnp,
                                  UKP: opts.ukip,
                                 }
    
    election.prepare_predicted_support() 
            
    if opts.single_election:
        assert election is not None, "No election data to work with"
        election.run()
        print election.result.summary
    elif opts.iterations > 0:
        assert election is not None, "No election data to work with"
        mc_sim = MonteCarlo(election)
        mc_sim.run(opts.iterations)
        
        # Report the results from the Monte Carlo run.
        print "Win percentages:"
        for party in sorted(mc_sim.win_counts.keys()):
            print "{0}: {1}".format(party,
                                    mc_sim.get_result_percentage(mc_sim.
                                                             win_counts[party]))
            
        print "Runner-up percentages:"
        for party in sorted(mc_sim.runnerup_counts.keys()):
            print "{0}: {1}".format(party,
                                    mc_sim.get_result_percentage(mc_sim.
                                                        runnerup_counts[party]))
            
    return
    
if __name__ == "__main__":
    electobot()    
    