#!/usr/bin/python
"""
Electobot
by Philip Brien (http://github.com/ZsigE)

Analysis and prediction tool based on the 2010 UK General Election results

Main module and data structures
"""

# Python imports
import optparse
import os
import cPickle as pickle
import logging

# Electobot imports
import csvparser
from constants import *
from candidate import Candidate
from constituency import Constituency

# Set up logging
logger = logging.getLogger("electobot")

# Classes
class Election(object):
    """Master class containing all information about the election."""
    
    def __init__(self):
        """Constructor."""
        
        # Data used to run the election
        self.constituencies = {}
        
        # Data generated by running the election
        self.parties = {}
        
        # Data generated by analyzing the results
        self.result = ""
        self.largest_party = None
        self.most_seats = 0
        
        return
    
    def populate_from_csv(self, csv_filename):
        """Create an Election from saved election data in CSV format."""
        
        # Extract all the information from the CSV file.
        rows = csvparser.csv_to_dicts(csv_filename)
        logger.debug("Found {0} rows".format(len(rows)))
           
        for row in rows:
            const = row["Seat"]
            logger.debug("Found seat {0}".format(const))
            if const not in self.constituencies:
                c = Constituency(const)
                self.constituencies[const] = c
            else:
                c = self.constituencies[const]
            c.region = row["Region"]
            candidates_2010 = row.candidates()
            c.votes_2005 = row.votes(2005)
            c.votes_2010 = row.votes(2010)
            c.turnout_2005 = float(row["Turn05"])
            c.turnout_2010 = float(row["Turn10"])

            # Copy the votes into the Candidate structures.
            c.candidates_2010 = []
            for party in c.votes_2010.keys():
                if party in candidates_2010.keys():
                    name = candidates_2010[party]
                else:
                    name = "Unknown"
                candidate = Candidate(name, party, c.votes_2010[party])
                c.candidates_2010.append(candidate)
                            
        return
    
    def predict_votes(self):
        """Predict the numbers of votes in each constituency."""
        
        for const_name in self.constituencies:
            const = self.constituencies[const_name]
            const.predict_votes()
            
        return
    
    def simulate(self):
        """Simulate the outcome of this election."""
        
        for const_name in self.constituencies:
            const = self.constituencies[const_name]
            const.simulate()
            if const.winning_party in self.parties.keys():          
                self.parties[const.winning_party].seats += 1
            else:
                party = Party(const.winning_party)
                party.seats = 1
                self.parties[const.winning_party] = party
        
        return
    
    def analyze(self):
        """Analyze the results of the election."""
        
        # First determine the largest party.
        self.most_seats = 0
        self.largest_party = None
        for party in self.parties:
            if self.parties[party].seats > self.most_seats:
                self.most_seats = self.parties[party].seats
                self.largest_party = party
                
        # Now determine whether they're past or behind the winning line (and
        # by how much).
        margin_of_victory = self.most_seats - NEEDED_FOR_MAJORITY
        if margin_of_victory >= 0:
            self.result = "{0} victory (majority {1})".format(
                                                             self.largest_party,
                                                             margin_of_victory)
        else:
            self.result = "Hung Parliament ({0} needs {1})".format(
                                                          self.largest_party,
                                                          (0-margin_of_victory))
        
        return

class Party(object):
    """Political party.  Used to classify Candidates."""
    
    def __init__(self, name):
        """Constructor.  Store just the name."""
        
        self.name = name
        self.seats = 0
        
        return
    
    
# Functions
def electobot():
    """Main function."""

    # Set up logging.
    formatter = logging.Formatter('%(asctime)s - %(name)s - '
                                  '%(levelname)s - %(message)s')
    handler = logging.FileHandler(LOG_FILE, mode="w")
    handler.setFormatter(formatter)
    logger.setLevel(LOG_LEVEL)
    logger.addHandler(handler)
     
    # Parse the input arguments.
    parser = optparse.OptionParser()
    parser.add_option("--csv", "-c", help="CSV file containing election data",
                      action="store", dest="csv")
    parser.add_option("--pickle", "-p",
                      help="File containing pickled election data",
                      action="store",
                      dest="pickle")
    parser.add_option("--savefile", "-s", 
                      help="Filename for saving pickled election data",
                      action="store",
                      dest="savefile")
    parser.add_option("--single-election", "-1",
                      help="Simulate a single election",
                      action="store_true",
                      dest="single_election")
    opts, args = parser.parse_args()
    assert len(args) == 0, "ELECTOBOT ACCEPTS NO ARGUMENT"
    
    election = None
    if opts.csv:
        # Populate the election from a CSV file.
        assert os.path.exists(opts.csv), "{0} does not exist".format(opts.csv)
        election = Election()
        election.populate_from_csv(opts.csv)
    elif opts.pickle:
        # Restore a saved election file from the pickled representation.
        assert os.path.exists(opts.pickle),                                    \
            "{0} does not exist".format(opts.pickle)
        with open(opts.pickle, "rb") as pickle_file:
            election = pickle.load(pickle_file)
        
    if opts.savefile:
        assert os.path.exists(opts.savefile),                                  \
            "{0} does not exist".format(opts.savefile)
        with open(opts.savefile, "wb") as save_file:
            pickle.dump(election, save_file, protocol=0)
            
    if opts.single_election:
        assert election is not None, "No election data to work with"
        election.predict_votes()
        election.simulate()
        election.analyze()
        print election.result
            
    return
    
if __name__ == "__main__":
    electobot()    
    